### ISSUE TITLE
常量ROOT定义的问题

### ISSUE THREAD

**Issue by renshan1990** [zhangbaitong/plume#1]
常量ROOT为具体项目入口；plume作为vendor下的component存在，具体项目应该对plume无侵入。以plume为基础构建的项目应该遵循一定的目录结构，根据这样的约定，可以把$_SERVER['DOCUMENT_ROOT']定义为全局常量ROOT。

**Comment by zhangbaitong** [comment]
1.通过约定目录结构来寻找相对路径提供默认实现
2.通过对plume框架的参数在外部定义
两种方式已经实现。
